name: Afterlife-Tours
favicon: null
layout_spectrum: 0.74714
typography_spectrum: 0.05769
title: Afterlife Tours
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f2390b'
    - '#fe8301'
    - '#676765'
  brandStrength: 0.16574064549058676
  lightness: 0.540307821938768
  saturation: 0
  rhythmicContrast: 0.2771800004411489
purpose: []
